#数据库连接
spring:
  datasource: # 数据源的相关配置
    driver-class-name: com.mysql.cj.jdbc.Driver # mysql驱动5.0以后+cj
    url: jdbc:mysql://localhost:3306/tool?useUnicode=true & characterEncoding=utf-8 &
      useSSL=true & serverTimezone=Asia/Shanghai # & serverTimezone=Asia/Shanghai一定要加，要不数据库时间会相差8个小时
    username: root
    password: 114678